import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home page",
  description: "Generated by AlaaKh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            width: "20%",
            marginBottom: "10px",
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/posts">posts</Link>
          <Link href="/articles">articles</Link>
          <Link href="/articles/featuredArticles">featuredArticles</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
